### ISSUE TITLE
Adjustment Required in LLM Service Component to Support GMC Chat QnA Pipeline

### ISSUE THREAD

**Issue by hteeyeoh** [opea-project/GenAIInfra#172]
- GMC is now able to support the chat QnA pipeline starting from the embedding component to the LLM component using the switch routerType.
- However, in the LLM service component, there is already a predefined environment variable called TGI_LLM_ENDPOINT, which fixes the route of the next TGI model to use (refer [llm.py](https://github.com/opea-project/GenAIComps/blob/main/comps/llms/text-generation/tgi/llm.py#L73) So it will ignore the switch condition we have set in the YAML file and always enter the predefined endpoints to invoke the LLM. 
- Similar design we also observed in other components like embedding and reranking where TEI_EMBEDDING_ENDPOINT and TEI_RERANKING_ENDPOINT are predefined as well .

-Below are the yaml changes with switch RouterType in gmc for chatQnA pipeline.
```
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: gmc.opea.io/v1alpha3
kind: GMConnector
metadata:
  labels:
    app.kubernetes.io/name: gmconnector
    app.kubernetes.io/managed-by: kustomize
    gmc/platform: xeon
  name: chatqa
  namespace: chatqa
spec:
  routerConfig:
    name: router
    serviceName: router-service
  nodes:
    root:
      routerType: Switch
      steps:
      - name: Embedding
        internalService:
          serviceName: embedding-svc
          config:
            endpoint: /v1/embeddings
      - name: TeiEmbedding
        internalService:
          serviceName: tei-embedding-svc
          isDownstreamService: true
      - name: Retriever
        data: $response
        internalService:
          serviceName: retriever-svc
          config:
            endpoint: /v1/retrieval
      - name: VectorDB
        internalService:
          serviceName: redis-vector-db
          isDownstreamService: true
      - name: Reranking
        data: $response
        internalService:
          serviceName: reranking-svc
          config:
            endpoint: /v1/reranking
      - name: TeiReranking
        internalService:
          serviceName: tei-reranking-svc
          config:
            endpoint: /rerank
          isDownstreamService: true
      - name: Llm
        data: $response
        internalService:
          serviceName: llm-svc
          config:
            endpoint: /v1/chat/completions
      - name: Tgi
        condition: model_id==intel
        internalService:
          serviceName: tgi-service-intel-neural
          config:
            endpoint: /generate
            LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
          isDownstreamService: true
      - name: Tgi
        condition: model_id==llama
        internalService:
          serviceName: tgi-service-llama
          config:
            endpoint: /generate
            LLM_MODEL_ID: openlm-research/open_llama_3b
          isDownstreamService: true
```
