### ISSUE TITLE
Use version control for deployment

### ISSUE THREAD

**Issue by Jiangbo-W** [opea-project/GenAIInfra#190]
Some of deployment YAML file use 'latest' tag as container image, which makes it difficult to report and track issues.

```
    spec:
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        image: opea/embedding-tei:latest
        imagePullPolicy: IfNotPresent
        name: embedding-deploy
        args:
        ports:
        - containerPort: 6000
      serviceAccountName: default
```
