### ISSUE TITLE
Migrate Microservices-Controller hostpath to config map format

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIInfra#39]
Evaluate options, pros and cons, and modify controller code.
Config map size limits should be adequate.

Create user documentation also.

**Comment by mkbhanda** [comment]
Iris research:

If you want to use a hostPath volume to mount the YAML files into your controller pod, you can do so by specifying a `hostPath` volume in your Kubernetes Deployment.
 
Here's an example:
 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-controller
spec:
  template:
    spec:
      containers:
      - name: my-controller
        image: my-controller:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        hostPath:
          path: /path/to/your/yaml/files
          type: Directory
```
 
In this example, the directory `/path/to/your/yaml/files` on the host is mounted as a volume at the path `/etc/config` in the controller pod. The YAML files will be available at the paths `/etc/config/file1.yaml`, `/etc/config/file2.yaml`, ..., `/etc/config/file10.yaml` in the pod.
 
Please note that `hostPath` volumes can be risky and may not work as expected on a cluster with multiple nodes, because they access the file system of the node where the pod is running. If the pod is rescheduled on a different node, the files will not be available. Therefore, `hostPath` volumes are typically used for single-node development environments and not recommended for production use.
 
In your controller code, you can read the YAML files from the path where they're mounted, as I described in the previous response.
 
Please note that this is a simplified example and might not cover all edge cases. For example, it assumes that the files are always available and that the file system always responds without errors. You might want to handle these and other edge cases depending on your specific needs.
