### ISSUE TITLE
[Requirement]Request for Adding TopologySpreadConstraints to ChatQnA Helm Chart

### ISSUE THREAD

**Issue by leslieluyu** [opea-project/GenAIInfra#401]
Is it possible to add topologySpreadConstraints to the ChatQnA Helm chart? This would help ensure that when we scale the pods across multiple nodes, they are scheduled evenly across those nodes.
Below is an example YAML snippet for reference:

```
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
               matchLabels:
                 app: tei-embedding-service-deploy
```
